import { writable } from 'svelte/store';

export default writable([
    {
        id: 0,
        type: `page`,
        title: `Home`,
        description: `This is a home page.`,
        canonical: `/`,
        path: `/index.html`,
        file: `index.html`,
        body: ``,
        components: [
            {
                id: null,
                element: null,
                children: [],
                tag: `h1`,
                options: {
                    contentEditable: true,
                    textContent: `Hello World`,
                },
            },
            {
                id: null,
                element: null,
                children: [],
                tag: `p`,
                options: {
                    contentEditable: true,
                    textContent: `Welcome to YOUR very own unstoppable website.`,
                },
            },
            {
                id: null,
                element: null,
                children: [],
                tag: `p`,
                options: {
                    contentEditable: true,
                    textContent: `WARNING: Progress will not be saved (yet)!`,
                },
            },
            {
                id: null,
                element: null,
                children: [],
                tag: `p`,
                options: {
                    contentEditable: true,
                    textContent: `IMPORTANT: Please don't try to build a full site for now, because it may be a very frustrating experience. This is NOT a stable release, and this is just for testing purposes!`,
                },
            },
            {
                id: null,
                element: null,
                children: [],
                tag: `p`,
                options: {
                    contentEditable: true,
                    textContent: `Anyway, have fun playing with this!`,
                },
            }
        ],
        mime: `text/html`,
    },
    {
        id: 1,
        type: `stylesheet`,
        path: `/style.css`,
        file: `style.css`,
        body: ``,
        mime: `text/css`,
    },
    {
        id: 2,
        type: `redirect`,
        path: `/ipfs-404.html`,
        file: `ipfs-404.html`,
        to: `/`,
        mime: `text/html`,
    },
    {
        id: 3,
        type: `security`,
        path: `/.well-known/security.txt`,
        file: `security.txt`,
        body: ``,
        mime: `text/plain`,
    },
    {
        id: 4,
        type: `ads`,
        path: `/ads.txt`,
        file: `ads.txt`,
        body: `placeholder.example.com, placeholder, DIRECT, placeholder`,
        mime: `text/plain`,
    },
    {
        id: 5,
        type: `browserconfig`,
        path: `/browserconfig.xml`,
        file: `browserconfig.xml`,
        body: ``,
        mime: `application/xml`,
    },
    {
        id: 6,
        type: `humans`,
        path: `/humans.txt`,
        file: `humans.txt`,
        body: ``,
        mime: `text/plain`,
    },
    {
        id: 7,
        type: `webmanifest`,
        path: `/manifest.webmanifest`,
        file: `manifest.webmanifest`,
        body: ``,
        mime: `application/manifest+json`,
    },
    {
        id: 8,
        type: `robots`,
        path: `/robots.txt`,
        file: `robots.txt`,
        body: ``,
        mime: `text/plain`,
    },
    {
        id: 9,
        type: `feed`,
        path: `/rss.xml`,
        file: `rss.xml`,
        body: ``,
        mime: `application/rss+xml`,
    },
    {
        id: 10,
        type: `sitemap`,
        path: `/sitemap.xml`,
        file: `sitemap.xml`,
        body: ``,
        mime: `application/xml`,
    }
]);
